---
version: '2'
services:
  dbzpostgres:
    build:
      dockerfile: Dockerfile
      context: ./dbz-postgres
    image: nanic/dbzpostgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: DebPostgres1!
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    depends_on:
      - dbzpostgres
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
      - 9999:9999
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9999
  kafka-connect:
    build:
      dockerfile: Dockerfile
      context: ./dbz-kafka-connect
    image: nanic/cp-kafka-connect:latest
    depends_on:
      - kafka
    ports:
      - 8083:8083
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:29092
      CONNECT_GROUP_ID: dbz-cdc-demo
      CONNECT_CONFIG_STORAGE_TOPIC: dbz-cdc-demo-config
      CONNECT_OFFSET_STORAGE_TOPIC: dbz-cdc-demo-offsets
      CONNECT_STATUS_STORAGE_TOPIC: dbz-cdc-demo-status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: localhost
      CONNECT_PLUGIN_PATH: /usr/share/java
  kafka-manager:
    image: nanic/cmak:latest
    ports:
      - 9000:9000
    depends_on:
      - kafka
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true